import { uid } from '../../lib/paneTree.js';
const empty = (title = 'Untitled') => ({ version: 1, title, description: '', nodes: [], edges: [], groups: [], fills: [] });
function makeDefaultVectorState(title = 'Untitled') { return empty(title); }
function parseVectorContent(content) { try { const p = JSON.parse(content); if (!p || !Array.isArray(p.nodes) || !Array.isArray(p.edges)) return empty(); return { ...empty(p.title || 'Untitled'), ...p, nodes: p.nodes.filter((n) => n?.id && Number.isFinite(n.x) && Number.isFinite(n.y)).map((n) => ({ ...n, boundTo: n.boundTo || null })), edges: p.edges.filter((e) => e?.id && e.a && e.b).map((e) => ({ ...e, thickness: Number.isFinite(e.thickness) && e.thickness > 0 ? e.thickness : 3, color: typeof e.color === 'string' ? e.color : '#5b8cff', groupId: e.groupId || null })), groups: Array.isArray(p.groups) ? p.groups : [], fills: Array.isArray(p.fills) ? p.fills.filter((f) => f && Number.isFinite(f.seedX) && Number.isFinite(f.seedY) && typeof f.color === 'string') : [] }; } catch { return empty(); } }
function serializeVectorState(state) { return JSON.stringify({ version: 1, title: state.title, description: state.description, nodes: state.nodes, edges: state.edges, groups: state.groups, fills: state.fills }, null, 2); }
function sortEdgesForRender(edges) { return edges.map((edge, index) => ({ edge, index })).sort((a, b) => a.edge.thickness - b.edge.thickness || a.index - b.index).map(({ edge }) => edge); }
function buildAdjacency(nodes, edges) { const out = new Map(nodes.map((n) => [n.id, []])); edges.forEach((e) => { if (out.has(e.a)) out.get(e.a).push(e.id); if (out.has(e.b)) out.get(e.b).push(e.id); }); return out; }
function addNode(state, point, boundTo = null) { const node = { id: uid('vector-node'), x: point.x, y: point.y, boundTo }; return { state: { ...state, nodes: [...state.nodes, node] }, node }; }
function addEdge(state, a, b, style = {}) { const edge = { id: uid('vector-edge'), a, b, thickness: style.thickness || 3, color: style.color || '#5b8cff', groupId: style.groupId || null }; return { state: { ...state, edges: [...state.edges, edge] }, edge }; }
function subdivideEdge(state, edgeId, atPoint) { const edge = state.edges.find((e) => e.id === edgeId); if (!edge) return state; const node = { id: uid('vector-node'), x: atPoint.x, y: atPoint.y, boundTo: null }; const left = { ...edge, id: uid('vector-edge'), b: node.id }, right = { ...edge, id: uid('vector-edge'), a: node.id }; return { ...state, nodes: [...state.nodes, node], edges: state.edges.flatMap((e) => e.id === edgeId ? [left, right] : [e]), groups: state.groups.map((g) => ({ ...g, edgeIds: g.edgeIds.flatMap((id) => id === edgeId ? [left.id, right.id] : [id]) })) }; }
function removeEdge(state, edgeId) { const edges = state.edges.filter((e) => e.id !== edgeId); const used = new Set(edges.flatMap((e) => [e.a, e.b])); return { ...state, edges, nodes: state.nodes.filter((n) => used.has(n.id)), groups: state.groups.map((g) => ({ ...g, edgeIds: g.edgeIds.filter((id) => id !== edgeId) })).filter((g) => g.edgeIds.length) }; }
function createGroup(state, edgeIds, label = 'Group') { const group = { id: uid('vector-group'), edgeIds: [...new Set(edgeIds)], parentGroupId: null, label }; return { ...state, groups: [...state.groups, group], edges: state.edges.map((e) => group.edgeIds.includes(e.id) ? { ...e, groupId: group.id } : e) }; }
function ungroup(state, groupId) { return { ...state, groups: state.groups.filter((g) => g.id !== groupId), edges: state.edges.map((e) => e.groupId === groupId ? { ...e, groupId: null } : e) }; }
function groupBoundingBox(group, nodes, edges) { const ids = new Set(group.edgeIds); const nodeIds = new Set(edges.filter((e) => ids.has(e.id)).flatMap((e) => [e.a, e.b])); const members = nodes.filter((n) => nodeIds.has(n.id)); if (!members.length) return null; const xs = members.map((n) => n.x), ys = members.map((n) => n.y); return { x: Math.min(...xs), y: Math.min(...ys), width: Math.max(...xs) - Math.min(...xs), height: Math.max(...ys) - Math.min(...ys) }; }
export { makeDefaultVectorState, parseVectorContent, serializeVectorState, sortEdgesForRender, buildAdjacency, addNode, addEdge, subdivideEdge, removeEdge, createGroup, ungroup, groupBoundingBox };
