function projectPointToSegment(p, a, b) { const dx = b.x - a.x, dy = b.y - a.y, d = dx * dx + dy * dy; const t = d ? Math.max(0, Math.min(1, ((p.x - a.x) * dx + (p.y - a.y) * dy) / d)) : 0; const point = { x: a.x + dx * t, y: a.y + dy * t }; return { point, t, distance: Math.hypot(p.x - point.x, p.y - point.y) }; }
function nearestNode(nodes, p, maxDist) { let best = null; nodes.forEach((node) => { const distance = Math.hypot(node.x - p.x, node.y - p.y); if (distance <= maxDist && (!best || distance < best.distance)) best = { node, distance }; }); return best; }
function nearestEdgePoint(edges, nodes, p, maxDist, excludeEdgeId) { const byId = new Map(nodes.map((n) => [n.id, n])); let best = null; edges.forEach((edge) => { if (edge.id === excludeEdgeId) return; const a = byId.get(edge.a), b = byId.get(edge.b); if (!a || !b) return; const hit = projectPointToSegment(p, a, b); if (hit.distance <= maxDist && (!best || hit.distance < best.distance)) best = { edge, ...hit }; }); return best; }
function axisSnap(from, to, force = false) { const dx = to.x - from.x, dy = to.y - from.y; if (force || Math.abs(dy) <= Math.abs(dx) * .2) return { ...to, y: from.y }; if (Math.abs(dx) <= Math.abs(dy) * .2) return { ...to, x: from.x }; return to; }
function alignmentCandidates(nodes, movingNodeId, tolerancePx) { const moving = nodes.find((n) => n.id === movingNodeId); if (!moving) return { x: [], y: [], snapped: null }; const x = [], y = []; nodes.forEach((n) => { if (n.id === movingNodeId) return; if (Math.abs(n.x - moving.x) <= tolerancePx) x.push(n.x); if (Math.abs(n.y - moving.y) <= tolerancePx) y.push(n.y); }); return { x, y, snapped: x.length || y.length ? { x: x[0] ?? moving.x, y: y[0] ?? moving.y } : null }; }
function tessellateStroke(nodes, edges) { const byId = new Map(nodes.map((n) => [n.id, n])); const out = new Map(); edges.forEach((edge) => { const a = byId.get(edge.a), b = byId.get(edge.b); if (!a || !b) return; const len = Math.hypot(b.x-a.x,b.y-a.y)||1, nx=-(b.y-a.y)/len*edge.thickness/2, ny=(b.x-a.x)/len*edge.thickness/2; out.set(edge.id,[{x:a.x+nx,y:a.y+ny},{x:b.x+nx,y:b.y+ny},{x:b.x-nx,y:b.y-ny},{x:a.x-nx,y:a.y-ny}]); }); return out; }
function pointInPolygon(p, poly) { let inside=false; for(let i=0,j=poly.length-1;i<poly.length;j=i++) { const a=poly[i],b=poly[j]; if ((a.y>p.y)!==(b.y>p.y) && p.x < (b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x) inside=!inside; } return inside; }
function distanceToStrokePolygon(polygon, p) { return pointInPolygon(p, polygon) ? 0 : Math.min(...polygon.map((a, i) => projectPointToSegment(p, a, polygon[(i+1)%polygon.length]).distance)); }
function hitTestEdge(edges,nodes,adjacency,p) { const polygons=tessellateStroke(nodes,edges,adjacency); return edges.find((e) => pointInPolygon(p,polygons.get(e.id)||[])) || null; }
export { projectPointToSegment, nearestNode, nearestEdgePoint, axisSnap, alignmentCandidates, tessellateStroke, distanceToStrokePolygon, hitTestEdge, pointInPolygon };
